### ISSUE TITLE
failed to run example

### ISSUE THREAD

**Issue by rain2307** [alttch/elbus#4]
platform: Ubuntu 22.04.2 LTS
rustc rustc 1.69.0 (84c898d65 2023-04-16)

` cargo run --example client_rpc_handler --features="ipc rpc"`

get error 

```
Error: Error { kind: Io, message: Some("No such file or directory (os error 2)") }
```

I changed  `/tmp/busrt.sock` to `localhost:port` and the error is:

```
Error: Error { kind: Io, message: Some("Connection refused (os error 111)") }
```

https://github.com/alttch/busrt/blob/9188419bdece0a58bd34b3434ad1635059b70739/examples/client_rpc_handler.rs#L76

**Comment by divi255** [comment]
Hi. You must have broker running on that socket path before running client examples.

You can use any one from broker / server examples or compile a sandalone busrtd binary using "server" feature.
